name: Setup PostgreSQL

on: [push]

jobs:
  setup-db:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Install PostgreSQL client
      run: sudo apt-get install postgresql-client

    - name: Execute SQL script for productos_auth
      run: |
        PGPASSWORD=password psql -h localhost -U user -d postgres -f productos_auth_init.sql

    - name: Execute SQL script for productos
      run: |
        PGPASSWORD=password psql -h localhost -U user -d postgres -f productos_init.sql
