name: Setup PostgreSQL

on: [push]

jobs:
  setup-db:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Install PostgreSQL client
      run: sudo apt-get install postgresql-client

    - name: Create productos_auth Database if not exists
      run: |
        PGPASSWORD=password psql -h localhost -U user -d postgres -c "SELECT 'CREATE DATABASE productos_auth' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'productos_auth')\gexec"

    - name: Execute SQL script for productos_auth
      run: |
        PGPASSWORD=password psql -h localhost -U user -d productos_auth -f productos_auth_init.sql

